"""add is_spoiler to reviews

Revision ID: 10890036401e
Revises: fe9f584cbc86
Create Date: 2026-03-05 01:52:02.914315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10890036401e'
down_revision: Union[str, Sequence[str], None] = 'fe9f584cbc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "reviews",
    sa.Column("is_spoiler", sa.Boolean(), server_default=sa.text("false"), nullable=False),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "is_spoiler")
    # ### end Alembic commands ###
