"""add movie visual embeddings

Revision ID: 7f50dc3f1f13
Revises: 5c9350d8a590
Create Date: 2026-05-02 14:55:03.949257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f50dc3f1f13'
down_revision: Union[str, Sequence[str], None] = '5c9350d8a590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_visual_embeddings_embedding_hnsw'), table_name='movie_visual_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('movie_visual_embeddings_movie_id_key'), 'movie_visual_embeddings', type_='unique')
    op.drop_index(op.f('ix_movie_visual_embeddings_movie_id'), table_name='movie_visual_embeddings')
    op.create_index(op.f('ix_movie_visual_embeddings_movie_id'), 'movie_visual_embeddings', ['movie_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_visual_embeddings_movie_id'), table_name='movie_visual_embeddings')
    op.create_index(op.f('ix_movie_visual_embeddings_movie_id'), 'movie_visual_embeddings', ['movie_id'], unique=False)
    op.create_unique_constraint(op.f('movie_visual_embeddings_movie_id_key'), 'movie_visual_embeddings', ['movie_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_movie_visual_embeddings_embedding_hnsw'), 'movie_visual_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
