"""add movie picker sessions

Revision ID: c98f79e8877e
Revises: eba63df5e7d3
Create Date: 2026-05-01 20:42:26.850997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98f79e8877e'
down_revision: Union[str, Sequence[str], None] = 'eba63df5e7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_picker_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=64), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('interpreted_mood', sa.String(length=64), nullable=False),
    sa.Column('secondary_moods', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('ranked_movie_ids', sa.JSON(), nullable=False),
    sa.Column('current_cursor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_picker_sessions_user_id'), 'movie_picker_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_picker_sessions_user_id'), table_name='movie_picker_sessions')
    op.drop_table('movie_picker_sessions')
    # ### end Alembic commands ###
