"""add user bio, cover photo, top movies

Revision ID: d414c7708df0
Revises: d1f2a3b4c5d6
Create Date: 2026-05-23 14:55:17.812909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd414c7708df0'
down_revision: Union[str, Sequence[str], None] = 'd1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_top_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 1 AND position <= 4', name='ck_user_top_movies_position'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_user_top_movies_user_movie'),
    sa.UniqueConstraint('user_id', 'position', name='uq_user_top_movies_user_position')
    )
    op.create_index(op.f('ix_user_top_movies_id'), 'user_top_movies', ['id'], unique=False)
    op.create_index(op.f('ix_user_top_movies_movie_id'), 'user_top_movies', ['movie_id'], unique=False)
    op.create_index(op.f('ix_user_top_movies_user_id'), 'user_top_movies', ['user_id'], unique=False)
    op.drop_constraint(op.f('directors_tmdb_id_key'), 'directors', type_='unique')
    op.drop_index(op.f('ix_directors_tmdb_id'), table_name='directors')
    op.create_index(op.f('ix_directors_tmdb_id'), 'directors', ['tmdb_id'], unique=True)
    op.drop_constraint(op.f('movie_directors_director_id_fkey'), 'movie_directors', type_='foreignkey')
    op.drop_constraint(op.f('movie_directors_movie_id_fkey'), 'movie_directors', type_='foreignkey')
    op.create_foreign_key(None, 'movie_directors', 'directors', ['director_id'], ['id'])
    op.create_foreign_key(None, 'movie_directors', 'movies', ['movie_id'], ['id'])
    op.add_column('users', sa.Column('bio', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('cover_photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_photo_url')
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'movie_directors', type_='foreignkey')
    op.drop_constraint(None, 'movie_directors', type_='foreignkey')
    op.create_foreign_key(op.f('movie_directors_movie_id_fkey'), 'movie_directors', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('movie_directors_director_id_fkey'), 'movie_directors', 'directors', ['director_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_directors_tmdb_id'), table_name='directors')
    op.create_index(op.f('ix_directors_tmdb_id'), 'directors', ['tmdb_id'], unique=False)
    op.create_unique_constraint(op.f('directors_tmdb_id_key'), 'directors', ['tmdb_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_top_movies_user_id'), table_name='user_top_movies')
    op.drop_index(op.f('ix_user_top_movies_movie_id'), table_name='user_top_movies')
    op.drop_index(op.f('ix_user_top_movies_id'), table_name='user_top_movies')
    op.drop_table('user_top_movies')
    # ### end Alembic commands ###
