"""add movie embeddings

Revision ID: eba63df5e7d3
Revises: a1b2c3d4e5f6
Create Date: 2026-04-30 19:52:26.982774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba63df5e7d3'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_embeddings_id'), 'movie_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_movie_embeddings_movie_id'), 'movie_embeddings', ['movie_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_embeddings_movie_id'), table_name='movie_embeddings')
    op.drop_index(op.f('ix_movie_embeddings_id'), table_name='movie_embeddings')
    op.drop_table('movie_embeddings')
    # ### end Alembic commands ###
