"""add diary_entry_id to reviews

Revision ID: fe9f584cbc86
Revises: 59921fc454c0
Create Date: 2026-02-18 18:08:51.373475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe9f584cbc86'
down_revision: Union[str, Sequence[str], None] = '59921fc454c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_diary_entries_id'), 'diary_entries', ['id'], unique=False)
    op.add_column('reviews', sa.Column('diary_entry_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reviews_diary_entry_id'), 'reviews', ['diary_entry_id'], unique=True)
    op.create_foreign_key(None, 'reviews', 'diary_entries', ['diary_entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_diary_entry_id'), table_name='reviews')
    op.drop_column('reviews', 'diary_entry_id')
    op.drop_index(op.f('ix_diary_entries_id'), table_name='diary_entries')
    op.alter_column('diary_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
